In [16]:
import pandas as pd
import numpy as np

train_url = 'data/train.csv'
test_url = 'data/test.csv'

train = pd.read_csv(train_url)
test = pd.read_csv(test_url)

In [17]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [18]:
train['Gender'] = train['Sex'].map({'male':1, 'female':0})
test['Gender'] = test['Sex'].map({'male':1, 'female':0})

In [19]:
for i in range(2):
    for j in range(1,4):
        median = train['Age'][(train['Gender'] == i) & (train['Pclass'] == j)].median()
        train['Age'][(train['Gender'] == i) & (train['Pclass'] == j)] = \
        train['Age'][(train['Gender'] == i) & (train['Pclass'] == j)].fillna(median)
        test['Age'][(test['Gender'] == i) & (test['Pclass'] == j)] = \
        test['Age'][(test['Gender'] == i) & (test['Pclass'] == j)].fillna(median)

/Users/mac/tensorflow/lib/python2.7/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/mac/tensorflow/lib/python2.7/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [20]:
train['Grade'] = train['Embarked'].map({'S': 1, 'C': 2, 'Q': 3})
train['Grade'] = train['Grade'].fillna(0.0)
test['Grade'] = test['Embarked'].map({'S': 1, 'C': 2, 'Q': 3})
test['Grade'] = test['Grade'].fillna(0.0)

In [21]:
train = train.drop(['PassengerId', 'Sex', 'Name', 'Ticket', 'Cabin', 'Embarked'], 1)
test = test.drop(['Sex', 'Name', 'Ticket', 'Cabin', 'Embarked'], 1)

Prepare the data for cross validation

In [22]:
from sklearn.cross_validation import cross_val_score


In [23]:
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score


clf_1 = tree.ExtraTreeClassifier()
clf_2 = RandomForestClassifier(random_state=1, n_estimators=100, min_samples_split=4, min_samples_leaf=2)
clf_3 = SVC()

# 1st attempt: Sex
fields = ['Gender']
print cross_val_score(clf_1, train[fields], train['Survived'])
print cross_val_score(clf_2, train[fields], train['Survived'])
print cross_val_score(clf_3, train[fields], train['Survived'])

[ 0.78787879  0.8013468   0.77104377]
[ 0.78787879  0.8013468   0.77104377]
[ 0.78787879  0.8013468   0.77104377]


In [24]:
# 2nd attempt: Sex, Pclass
fields = ['Gender', 'Pclass']
print cross_val_score(clf_1, train[fields], train['Survived'])
print cross_val_score(clf_2, train[fields], train['Survived'])
print cross_val_score(clf_3, train[fields], train['Survived'])

[ 0.75757576  0.8013468   0.77104377]
[ 0.75757576  0.8013468   0.77104377]
[ 0.75757576  0.8013468   0.77104377]


In [25]:
# 3rd attempt: Sex, Pclass, Age
fields = ['Gender', 'Pclass', 'Fare']
print cross_val_score(clf_1, train[fields], train['Survived'])
print cross_val_score(clf_2, train[fields], train['Survived'])
print cross_val_score(clf_3, train[fields], train['Survived'])

[ 0.73737374  0.81481481  0.81818182]
[ 0.74410774  0.81481481  0.80808081]
[ 0.75420875  0.8013468   0.77104377]


In [26]:
# 4th attempt: Sex, Pclass, Age, SibSp
fields = ['Gender', 'Pclass', 'Age', 'SibSp']
print cross_val_score(clf_1, train[fields], train['Survived'])
print cross_val_score(clf_2, train[fields], train['Survived'])
print cross_val_score(clf_3, train[fields], train['Survived'])

[ 0.76430976  0.80808081  0.7979798 ]
[ 0.8013468   0.83164983  0.81818182]
[ 0.78787879  0.82828283  0.82491582]


In [27]:
# 5th attempt: Sex, Pclass, Age, SibSp, Parch
fields = ['Gender', 'Pclass', 'Age', 'SibSp', 'Parch']
print cross_val_score(clf_1, train[fields], train['Survived'])
print cross_val_score(clf_2, train[fields], train['Survived'])
print cross_val_score(clf_3, train[fields], train['Survived'])

[ 0.76094276  0.81144781  0.75420875]
[ 0.79124579  0.83838384  0.83164983]
[ 0.77777778  0.82828283  0.82491582]


In [28]:
# 6th attempt: Sex, Pclass, Age, SibSp, Parch, Fare
fields = ['Gender', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']
print cross_val_score(clf_1, train[fields], train['Survived'])
print cross_val_score(clf_2, train[fields], train['Survived'])
print cross_val_score(clf_3, train[fields], train['Survived'])

[ 0.75757576  0.75757576  0.76767677]
[ 0.79461279  0.85185185  0.84175084]
[ 0.68013468  0.71380471  0.74074074]


In [29]:
# 7th attempt: Sex, Pclass, Age, SibSp, Parch, Fare, Embarked
fields = ['Gender', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Grade']
print cross_val_score(clf_1, train[fields], train['Survived'])
print cross_val_score(clf_2, train[fields], train['Survived'])
print cross_val_score(clf_3, train[fields], train['Survived'])

[ 0.75084175  0.8013468   0.74747475]
[ 0.8013468   0.84175084  0.82828283]
[ 0.67340067  0.71043771  0.71717172]


In [30]:
clf_2.fit(train[fields], train['Survived'])

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=2, min_samples_split=4,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=1, verbose=0, warm_start=False)

In [31]:
test['Fare'][test['Fare'].isnull()] = test['Fare'][test['Pclass'] == 3].median()


/Users/mac/tensorflow/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [32]:
test['Survived'] = clf_2.predict(test[fields])

In [33]:
test[['PassengerId', 'Survived']].to_csv('result.csv', index=False)